//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod custom_orders;
pub mod custom_recharge;
pub mod custom_user;
pub mod sys_carousel;
pub mod sys_image;
pub mod sys_resource_category;
pub mod sys_resource_images;
pub mod sys_resource_language;
pub mod sys_resources;
pub mod sys_user;
pub mod sys_website_info;
pub mod withdrawals;
