//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::custom_orders::Entity as CustomOrders;
pub use super::custom_recharge::Entity as CustomRechargeRecords;
pub use super::custom_user::Entity as CustomUser;
pub use super::sys_carousel::Entity as SysCarousel;
pub use super::sys_image::Entity as SysImage;
pub use super::sys_resource_category::Entity as SysResourceCategoty;
pub use super::sys_resource_images::Entity as SysResourceImages;
pub use super::sys_resource_language::Entity as SysResourceLanguage;
pub use super::sys_resources::Entity as SysResources;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_website_info::Entity as SysWebsiteInfo;
pub use super::withdrawals::Entity as Withdrawals;
