//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_uuid: String,
    pub resource_name: String,
    pub description: Option<String>,
    pub description_file_path: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((65, 2)))")]
    pub resource_price: u64,
    pub category: String,
    pub language: String,
    pub resource_link: String,
    pub create_date: DateTime,
    pub create_user_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
