//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_website_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub version: Option<String>,
    pub public_record: Option<String>,
    pub website_record: Option<String>,
    pub sys_kefu: Option<String>,
    pub website_icon: Option<String>,
    pub custom_login_img: Option<String>,
    pub admin_login_img: Option<String>,
    pub home_page_img: Option<String>,
    pub home_page_carousel_img: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
