server:
  name: "source_website_salvo_sea"
  address: "0.0.0.0:5800"
  ssl: false
  cors_allow_origin:
    - "http://localhost:5173"

database:
  database_url: "mysql://root:99158194@127.0.0.1:3306/resource_website"

cache:
  redis_url: "redis://127.0.0.1:6379"
#  redis_url: "redis://:密码@localhost:6379"

jwt:
  jwt_secret: "secret"
  jwt_exp: 6000

tariff:
  tariff_1000: 0.05
  tariff_100: 0.10

cert:
  cert: "config/certs/cert.pem"
  key: "config/certs/key.pem"

log:
  filter_level: "debug" # Available options: "debug", "info", "warn", "error"
  with_ansi: true
  to_stdout: true
  directory: "./logs"
  file_name: "my-service.log"
  rolling: "daily" # Available options: "minutely", "hourly", "daily", "never"
